# Generated by Django 4.2.1 on 2023-05-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
